### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by ronikiienko** [sokorototo/worleyjs#10]
I am creating the app that need worley noise for the purpose that is not for textures or such things.
For example, it can need just 50 coordinates and noise value for them (which can be get using noise.pixel() method)
So, the problem is that in my case, that i need to calculate noise value when i already call noise.pixel() method.
Do your library create whole matrix as soon as i create instance using new Worley(...)?

I'm sorry if question can be inaproppriate as an issue. Thanks for your work :)

**Comment by sokorototo** [comment]
Creating a new Worley instance will not calculate noise values for all pixels, it's only done when calling `Worley.ImageData`. `Worley.pixel` only calculates the value for that one pixel, meaning it's very fast
