### ISSUE TITLE
Periodic tiles

### ISSUE THREAD

**Issue by unicomp21** [sokorototo/worleyjs#9]
How do I use this to create periodic/repeating 2d/3d tiles which I can leverage on a gpu via texture2d and texture3d lookups?

**Comment by sokorototo** [comment]
What do you mean by `periodic/repeating 2d/3d tiles`?

**Comment by sokorototo** [comment]
Maybe use `noise.Texture.ImageData()` then build an `ImageData`, then convert the `ImageData` to an `ImageBitmap` which you can send to the GPU? [Link](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap#parameters)

**Comment by unicomp21** [comment]
here is an example
https://github.com/stegu/perlin-noise/blob/master/src/noise1234.h#L39

**Comment by sokorototo** [comment]
Ooooh🙄. I do not know shader programming. I wish I could help but I am just learning glsl. Maybe try to elaborate it, I dunno, `synchronously`? Got some texture examples?

**Comment by unicomp21** [comment]
No worries, didn't realize that.

**Comment by Gaffen** [comment]
Sorry to resurface this - but I'm looking for a similar solution for a similar application. I want to create what could essentially be seen as a cylindrical sample. A tileable noise sample in one axis. At the moment I'm doing this my manually adding random crests to the noise sample, and then duplicating the ones at the beginning/end of the sample and repeating them off-canvas. I haven't quite managed to get this to tile perfectly yet but I think that's an implementation issue on my end. It would be pretty cool to see this implemented as a feature though!

**Comment by sokorototo** [comment]
I'll look into methods for tiling noise samples with Worley Noise, give me a few days

**Comment by Gaffen** [comment]
Thanks for the speedy response, I really enjoy the design of your library - very easy to use!

This is a very rough and ready implementation as I'm just doing some sketching on a low stake personal project, but if it helps, here's how I solved the problem:
https://github.com/Gaffen/LowRez/blob/feature/tilingVoronoi/src/utils/flameTexture.js#L102-L146

I was initially looking for ways to integrate directly with perlin/simplex noise, but I don't think that's entirely necessary/relevant to this library.

You could also look at creating the noise in three dimensions and doing it along the surface of a cylinder (it's how I've done it in the past). It's probably a little more efficient than my quick 'n' dirty overlap calculation 😅

**Comment by sokorototo** [comment]
You could scatter crests in a sizeable 2d area (1000x1000), and make sure they are tiling. Then when you want to insert the crests you need, then pick those in your current window. You can then insert those use those crests to generate the texture. It's fast too, but thanks for the tip
